### ISSUE TITLE
readOnly on transactional service fails the unit test

### ISSUE THREAD

**Issue by foxmano** [tednaleid/build-test-data#48]
Hi,
I'm very new to Grails (with only a Java background) so I'm not sure if it's a bug or a feature. But I noticed a strange behavior using the build-test-data plugin. When I set a service method as readOnly=true, the domain objects previously created with build() are not saved, unless I read my Domain objects before calling my service.
Here is the code to reproduce my problem:

============= in /grails-app/domain =============
package mypackage

class MyDomain {

	String myField
}

============= in /grails-app/services/mypackage =============
package mypackage

import grails.transaction.Transactional

@Transactional
class MyService {

	def listEntities() {
		MyDomain.list()
	}

	@Transactional(readOnly=true)
	def listEntitiesReadOnly() {
		MyDomain.list()
	}

============= in /test/unit/mypackage =============
package mypackage

import grails.buildtestdata.mixin.Build
import grails.test.mixin.TestFor
import spock.lang.Specification

@TestFor(MyService)
@Build(MyDomain)
class MyServiceSpec extends Specification {

	void "test list() using default"() {
		given:
		MyDomain.build()

		when:
		def res = service.listEntities()

		then:
		res.size()==1
	}
	void "test list() with service read-only"() {
		given:
		MyDomain.build()

		when:
		def res = service.listEntitiesReadOnly()

		then:
		res.size()==1
	}
	void "test list() with service read-only with assert before"() {
		given:
		MyDomain.build()
		MyDomain.list()

		when:
		def res = service.listEntitiesReadOnly()

		then:
		res.size()==1
	}
}
==========================

I'm using Grails 2.4.4 with build-test-data 2.4.0.

The first and third test work, not the second one. Does anybody know why?
Thanks in advance.

**Comment by tednaleid** [comment]
I'm betting this is a side effect of the unit test `@Build` annotation not really matching up with how the "real" transactions work, and it's marking all of the objects touched in the 

I'd bet that if you took build-test-data out of the picture and used the `@Mock` annotation (instead of `@Build`) and did `new Domain().save(myField: 'foo')` in the 2nd test that it'd exhibit the same behavior.

If that's true, I'd submit that as a bug against the grails core, but really when you start getting into transactionally annotated service methods, I've found that the mock-grails stuff is fairly lacking and has lots of edge cases like this.  You'd probably be better off with an integration test if you really need to have stuff saved in a database and make sure that the transactional nature of your code is what you expect.  Unit tests aren't testing the real code path.

**Comment by foxmano** [comment]
Thanks for your quick reply.
You are right, it has the exact same behavior using the @Mock + save(). I will then raise the bug/behavior against the grails core, sorry for having created this issue here!
I have always favored unit testing vs integration testing, mainly for speed and performance reasons, but I guess I should rather use integration tests to get the "real" code execution as you said.
Thanks again
